export const CART_ACTIONS_TYPE = {

    SET_IS_CART_HIDDEN: 'SET_IS_CART_HIDDEN', 
    SET_CART_ITEMS: 'SET_CART_ITEMS', 
    SET_CART_QUANTITY: 'SET_CART_QUANTITY', 
    SET_CART_PRICE: 'SET_CART_PRICE'

}